name: tempsite-dtm-cleaning-web

services:
  app:
    image: ${IMAGE:-ghcr.io/whenparty/temp-dtm-cleaning-web:latest}
    container_name: dtm-cleaning-web
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dtm-cleaning-web.rule=Host(`dtm-cleaning-web.temp.nii.au`)'
      - 'traefik.http.routers.dtm-cleaning-web.entrypoints=web'
      - 'traefik.http.services.dtm-cleaning-web.loadbalancer.server.port=80'
    networks:
      - tempsites

networks:
  tempsites:
    external: true
